language: c

os:
        - linux
        - osx

addons:
        apt:
                packages:
                        - libcppunit-dev
before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
                brew update && brew install cppunit ;
          fi

script: make && make test
